# Generated by Django 3.1.14 on 2023-12-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='my_styles',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='style',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
