# Generated by Django 3.1.14 on 2023-12-11 06:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default=None, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('nb_pieces', models.IntegerField()),
                ('nb_rooms', models.IntegerField()),
                ('surface', models.IntegerField()),
                ('nb_floors', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default=None, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieceFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PieceOfHouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface', models.FloatField()),
                ('features', models.ManyToManyField(to='classifieds.PieceFeature')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='classifieds.home')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.piece')),
            ],
        ),
    ]
