# Generated by Django 3.1.14 on 2023-12-11 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecefeature',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piece',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homefeature',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='home',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='home',
            name='classified',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='classifieds.classified'),
        ),
        migrations.AddField(
            model_name='home',
            name='features',
            field=models.ManyToManyField(to='classifieds.HomeFeature'),
        ),
    ]
