# Generated by Django 3.1.14 on 2024-01-16 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pieceofhouse',
            name='features',
            field=models.ManyToManyField(to='classifieds.PieceFeature'),
        ),
        migrations.AddField(
            model_name='pieceofhouse',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='classifieds.home'),
        ),
        migrations.AddField(
            model_name='pieceofhouse',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.piece'),
        ),
        migrations.AddField(
            model_name='piecefeature',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piece',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homefeature',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='home',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='home',
            name='features',
            field=models.ManyToManyField(blank=True, to='classifieds.HomeFeature'),
        ),
        migrations.AddField(
            model_name='classified',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classified', to='classifieds.home'),
        ),
        migrations.AddField(
            model_name='classified',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifieds.style'),
        ),
    ]
