# Generated by Django 3.1.14 on 2023-12-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20231211_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
