# Generated by Django 3.1.14 on 2023-12-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_classified_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='nb_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='nb_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='nb_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='surface',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
