# Generated by Django 3.1.14 on 2023-12-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_auto_20231211_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='classified',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='classifieds.classified'),
        ),
    ]
