# Generated by Django 3.1.14 on 2023-12-11 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0005_auto_20231211_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='classified',
        ),
        migrations.AddField(
            model_name='classified',
            name='home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classified', to='classifieds.home'),
        ),
    ]
