# Generated by Django 3.1.14 on 2023-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0007_auto_20231213_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='features',
            field=models.ManyToManyField(blank=True, to='classifieds.HomeFeature'),
        ),
    ]
