# Generated by Django 3.1.14 on 2023-12-18 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0009_auto_20231218_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='style', to='classifieds.style'),
        ),
    ]
