# Generated by Django 4.1.3 on 2023-12-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0010_auto_20231218_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='corrections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classified',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classifieds.style'),
        ),
    ]
