# Generated by Django 3.1.14 on 2024-01-04 09:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0011_classified_corrections_alter_classified_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
