# Generated by Django 3.1.14 on 2024-01-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0012_auto_20240104_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='text',
            field=models.TextField(),
        ),
    ]
