# Generated by Django 3.1.14 on 2024-01-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0013_auto_20240104_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
