# Generated by Django 3.1.14 on 2024-01-10 06:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0014_classified_is_ai_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('corrections', models.TextField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, default=datetime.date(2024, 1, 10), null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=None, max_length=255, null=True, unique=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='classifieds.home')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classifieds.style')),
            ],
        ),
    ]
