# Generated by Django 3.1.14 on 2024-01-10 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0015_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
