# Generated by Django 3.1.14 on 2024-01-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0016_auto_20240110_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifieds.style'),
        ),
    ]
